# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a88624b16499842c9361e421e6e20bbe8cda1f61be9805c60c3eaf0c116e779c60124b70ec6904591e70a88a64fcdced4a0bda163286be83ab5838cfeb0a409a

test:
  secret_key_base: 9a55161367727d268fd0087ae1c4c5b19fcf291891b8660ae990730062e639b835967ce0b40c2d4df53ef021b4850b5da67de085935a93089e4d99abb79565be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
